# Generated by Django 5.2.8 on 2025-11-24 10:09

from django.db import migrations
from django.apps.registry import Apps
from slugify import slugify
from django.shortcuts import get_object_or_404
from django.db.models import Avg
import json
from pathlib import Path
import random
import string
import bleach

from accounts.models import AppUser as AppUserModel
from products.models import Product as ProductModel
from products.models import ProductImg as ProductImgModel
from products.models import Category as CategoryModel
from reviews.models import Review as ReviewModel

from reviews.ml_service import get_predictor_instance


ALLOWED_ATTRIBUTES = {
    'a': ['href', 'title'],
    'img': ['src','alt']
}

def _random_string(length:int = 10):
    return ''.join(random.choices(string.ascii_letters + string.digits, k=length))

def clean_description(content:str):
    return bleach.clean(
        content,
        tags=['h1','h2', 'h3', 'h4','h5','strong','a','i','b', 'li','ul','p','img','div'],
        attributes=ALLOWED_ATTRIBUTES,
        strip=True
    )

def load_product_data(apps: Apps, schema_editor):
    model_instance = get_predictor_instance()

    db_alias = schema_editor.connection.alias

    AppUser: AppUserModel = apps.get_model('accounts', 'AppUser')
    Product: ProductModel = apps.get_model('products', 'Product')
    ProductImg: ProductImgModel = apps.get_model('products', 'ProductImg')
    Category: CategoryModel = apps.get_model('products', 'Category')
    Review: ReviewModel = apps.get_model('reviews', 'Review')

    # make role via groups of Django
    Group = apps.get_model("auth", "Group")
    for role_name in ['Admin','User']:
        group, created = Group.objects.using(db_alias).get_or_create(name=role_name)
        if created:
            # You can also assign permissions here if needed
            print(f"Group '{role_name}' created successfully.")

    user_group = Group.objects.get(name = 'User')


    # make categories with no parent
    for name in ['nhà cửa - đời sống','điện gia dụng','laptop - máy tính', 'làm đẹp - sức khỏe']:
        Category.objects.create(
            name = name,
            slug = slugify(name),
            parent=None
        )

    # 1. Define File Path (Relative to the Migration File)
    app_dir = Path(__file__).resolve().parent.parent.parent.parent # Finds the app directory
    json_path = app_dir / 'crawl_data2db' / 'master_data.json'
    
    # 2. Read File and Load JSON
    master_data = None
    try:
        with open(json_path, 'r') as f:
            master_data = json.load(f)
            print('load json data')

    except FileNotFoundError:
        # Crucial for development safety
        print("Initial product JSON file not found")
        return

    assert master_data is not None
    for parent_cate_data_dict in master_data:
        parent_cat = parent_cate_data_dict['master_category_name']
        data = parent_cate_data_dict['data']

        for prod_data in data:
            product_data = prod_data['product_data']
            review_data: list[str] = prod_data['review']

            # make child categories
            parent_category = get_object_or_404(Category, name=parent_cat, parent=None)
            subcategory, _ = Category.objects.using(db_alias).get_or_create(
                name=product_data['category_name'],
                slug=slugify(product_data['category_name']),
                parent=parent_category
            )

            # insert products
            new_product = Product.objects.using(db_alias).create(
                name = product_data['product_name'],
                slug = slugify(product_data['product_name'][:255]),
                category = subcategory,
                description = clean_description(product_data['description']),
                brand_name = product_data['brand_name'],
                price = product_data['price'],
                stock = product_data['stock'],
                is_active = True,
                thumbnail_url = product_data['thumbnail_url']
            )
            
            # insert images
            ProductImg.objects.using(db_alias).bulk_create([
                ProductImg(
                    product = new_product,
                    image_url = _img_url
                )
                for _img_url in product_data['image_urls']
            ])

            # insert reviews
            if len(review_data) > 0:
                # infer review text as batch prediction
                predict_sentiment: list[bool] = model_instance.forward(review_data)
                assert len(predict_sentiment) == len(review_data), f'type predict : {type(predict_sentiment)}, {predict_sentiment}'
                
                # make random user
                user_list = []
                for  _ in range(len(review_data)):
                    rand_last_name = _random_string(5)
                    rand_first_name = _random_string(7)
                    rand_email = f'{_random_string(13)}@gmail.com'
                    user_list.append(
                        AppUser(
                            password = _random_string(12),
                            is_superuser = False, 
                            username = f'{rand_first_name}_{rand_last_name}',
                            first_name = rand_first_name,
                            last_name = rand_last_name, 
                            email = rand_email, 
                            is_staff = True,
                    ))

                # insert users
                list_user_model: list[AppUserModel] = AppUser.objects.using(db_alias).bulk_create(user_list)
                
                # assign `User` group
                for user in list_user_model:
                    user.groups.add(user_group)

                # insert review
                Review.objects.using(db_alias).bulk_create([
                    Review(
                        product = new_product,
                        user = user,
                        content = review_content,
                        score = _score
                    )
                    for user, review_content, _score in zip(list_user_model, review_data, predict_sentiment)
                ])


    # manually update mean rating in product
    # signal wont triggered in migrations
    for product in Product.objects.using(db_alias).all():
        # Calculate the mean based on the 'score' field
        average_result = product.reviews.exclude(score__isnull=True).aggregate(Avg('score'))
        
        # Update the Product and save
        product.mean_rating = average_result['score__avg']
        # Use update_fields
        product.save(update_fields=['mean_rating'])
        

class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('orders', '0001_initial'),
        ('products', '0001_initial'),
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(load_product_data),
    ]
